### PR TITLE
Added Commands to list and install PHP versions

### PR DESCRIPTION
**Pull request by TobyMaxham**
Hi there,

we havent done any changes for a while.

Since we handle a lot of servers now, it's become quite dificult to handle them all.
With this change, it is now possible to list all installed PHP versions of the current server and also install new versions.

The console will stay open so you can watch the installation process.

For a futre update it would be nice, to use the CLI to switch the global PHP version. So you can change it eg to PHP 8.3 without login to Dashboard.

Thanks!

### CODE REVIEW

**Comment by NorbertFox** [comment]
This are only new Commands. Are you sure there aren't any dependencies missing?
I'm not sure who can compile the new sources

**Comment by TobyMaxham** [comment]
I think we should build it only for a new version. ok?

**Comment by NorbertFox** [comment]
Do you add the compiled version or not?

**Comment by TobyMaxham** [comment]
So i meen, we only should compile it again in a new version. So I wont add the compiled version in my PR

**Pull request merged**
